version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bsa_monitoring
      MYSQL_USER: test
      MYSQL_PASSWORD: a2374168
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    ports:
      - "127.0.0.1:81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: spring-boot-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bsa_monitoring
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: a2374168

volumes:
  mysql-data:
